trayectos_data = [
    {
        'numero': 0,
        'nombre': 'Trayecto Inicial',
        'tipo': 'Inicial',
        'duracion_semanas': 12,
        'duracion_horas': None,
        'creditos_minimos': 10,
        'creditos_maximos': 10,
        'numero_tramos': 1,
        'objetivos': 'Introducir a los participantes en los conceptos básicos y fundamentales de la informática y preparar el terreno para los trayectos posteriores. Este trayecto podría enfocarse en nivelar los conocimientos básicos de los estudiantes y familiarizarlos con el entorno de aprendizaje y las herramientas que utilizarán.',
        'competencias': None,
        'perfil_egreso': None,
        # No incluyas 'tramos' ni 'unidades_curriculares' aquí
    },
    {
        'numero': 1,
        'nombre': 'Trayecto I',
        'tipo': 'Profesional',
        'duracion_semanas': 36,
        'duracion_horas': None,
        'creditos_minimos': None,
        'creditos_maximos': None,
        'numero_tramos': 3,
        'objetivos': 'Establecer las bases técnicas y teóricas en informática. Los participantes aprenden a operar, ensamblar, y mantener equipos de computación, así como a desarrollar algoritmos básicos y proporcionar soporte técnico.',
        'competencias': None,
        'perfil_egreso': None,
    },
    {
        'numero': 2,
        'nombre': 'Trayecto II',
        'tipo': 'Profesional',
        'duracion_semanas': 36,
        'duracion_horas': None,
        'creditos_minimos': None,
        'creditos_maximos': None,
        'numero_tramos': 3,
        'objetivos': 'Profundizar en el desarrollo de software y la administración de redes. Los participantes comienzan a trabajar con algoritmos más complejos, desarrollo de software bajo estándares de calidad, y administración de redes de área local.',
        'competencias': None,
        'perfil_egreso': None,
    },
    {
        'numero': 3,
        'nombre': 'Trayecto III',
        'tipo': 'Profesional',
        'duracion_semanas': 36,
        'duracion_horas': None,
        'creditos_minimos': None,
        'creditos_maximos': None,
        'numero_tramos': 3,
        'objetivos': 'Enfocarse en el desarrollo de aplicaciones informáticas y la gestión de proyectos. Los participantes aprenden a aplicar principios de ingeniería de software, diseñar y administrar bases de datos, y gestionar proyectos informáticos.',
        'competencias': None,
        'perfil_egreso': None,
    },
    {
        'numero': 4,
        'nombre': 'Trayecto IV',
        'tipo': 'Profesional',
        'duracion_semanas': 36,
        'duracion_horas': None,
        'creditos_minimos': None,
        'creditos_maximos': None,
        'numero_tramos': 3,
        'objetivos': 'Completar la formación con competencias avanzadas en auditoría de sistemas, diseño e implementación de redes informáticas, y comunicación técnica en inglés. Este trayecto prepara a los participantes para integrarse plenamente al campo profesional de la informática.',
        'competencias': None,
        'perfil_egreso': None,
    },
]