unidades_tray0_tramo1 = [
    {
        'codigo': 'MAC015',
        'nombre': 'Matemática',
        'nombre_corto': 'MAC',
        'area': None,
        'subarea': None,
        'eje_formativo': None,
        'horas_teoricas': 60,
        'horas_practicas': 10,
        'horas_laboratorio': 5,
        'horas_trabajo_independiente': 5,
        'horas_totales': None,
        'unidades_credito': 5,
        'tipo': 'Obligatoria',
        'caracter': None,
        'modalidad': None,
        'complejidad': None,
        'prelaciones': None,
        'competencias_genericas': None,
        'competencias_especificas': None,
        'saberes_cognitivos': None,
        'saberes_procedimentales': None,
        'saberes_actitudinales': None,
        'estrategias_ensenanza': None,
        'recursos_didacticos': None,
        'evaluacion': None,
        'bibliografia': None,
        'homologacion_clave': None,
        'clave_especial': None,
        'tramo_numero': 1
    },
    {
        'codigo': 'PNS013',
        'nombre': 'Proyecto Nacional y Nueva Ciudadanía',
        'nombre_corto': 'PNS',
        'area': None,
        'subarea': None,
        'eje_formativo': None,
        'horas_teoricas': 60,
        'horas_practicas': 6.5,  # Redondeado
        'horas_laboratorio': 4,
        'horas_trabajo_independiente': 2.5,  # Redondeado
        'horas_totales': None,
        'unidades_credito': 3,
        'tipo': 'Obligatoria',
        'caracter': None,
        'modalidad': None,
        'complejidad': None,
        'prelaciones': None,
        'competencias_genericas': None,
        'competencias_especificas': None,
        'saberes_cognitivos': None,
        'saberes_procedimentales': None,
        'saberes_actitudinales': None,
        'estrategias_ensenanza': None,
        'recursos_didacticos': None,
        'evaluacion': None,
        'bibliografia': None,
        'homologacion_clave': None,
        'clave_especial': None,
        'tramo_numero': 1
    },
    {
        'codigo': 'IPC012',
        'nombre': 'Introduccion a los Proyectos y al PNF',
        'nombre_corto': 'IPC',
        'area': None,
        'subarea': None,
        'eje_formativo': None,
        'horas_teoricas': 60,
        'horas_practicas': 4.5,  # Redondeado
        'horas_laboratorio': 2,
        'horas_trabajo_independiente': 2.5,  # Redondeado
        'horas_totales': None,
        'unidades_credito': 2,
        'tipo': 'Obligatoria',
        'caracter': None,
        'modalidad': None,
        'complejidad': None,
        'prelaciones': None,
        'competencias_genericas': None,
        'competencias_especificas': None,
        'saberes_cognitivos': None,
        'saberes_procedimentales': None,
        'saberes_actitudinales': None,
        'estrategias_ensenanza': None,
        'recursos_didacticos': None,
        'evaluacion': None,
        'bibliografia': None,
        'homologacion_clave': None,
        'clave_especial': None,
        'tramo_numero': 1
    },
]